function [means, Sbetas]= roi_contrast_meanLocal_RegSuccessViewEmo(mask)
% extract mean beta values in a given contrast

% Input: the mask name for the region of interest (ROI) as a character
% string, without the .nii ending

contrasts = {'RegSuccess-ViewEmoME'}; % contrast name to pull 
ipath = '/Users/username/fMRI_models/GLM_ER_first_level/cons4fsl'; % where first-level contrast data are stored
spath = '/Users/username/fMRI_models/GLM_ER_first_level/'; % location of the SPM.mat (in each participant's folder within this folder)
mpath = '/Users/username/fMRI_models/anatomical_masks/';

cd([ipath])
close all

% take all 31 people for whom we have both good food choice and emotion data 
subj_ids = {'1003', ...
    '1004', ...
    '1006', ...
    '1007', ...
    '1008', ...
    '1009', ...
    '1014', ...
    '1016', ...
    '1019', ...
    '1020', ...
    '1021', ...
    '1023', ...
    '1027', ...
    '1030', ...
    '1032', ...
    '1034', ...
    '1037', ...
    '1039', ...
    '1040', ...
    '1043', ...
    '1046', ...
    '1047', ...
    '1049', ...
    '1050', ...
    '1052', ...
    '1054', ...
    '1066', ...
    '1067', ...
    '1068', ...
    '1071', ...
    '1072'};

% Get all data in the mask
s=load([spath subj_ids{1} '/SPM.mat']); % can be any participant as long as their parameters are the same

XYZ  = s.SPM.xVol.XYZ;
Z = spm_get_data([mpath mask '.nii'],XYZ);  

% select the list of voxels > 0 in the mask
included_voxels=XYZ(:,Z>0);
clear Z
cd([ipath])
Sbetas =zeros(length(subj_ids),length(contrasts));

for t=1:length(subj_ids)
    cd(subj_ids{t});
    sub = subj_ids{t};
    con_file = {[contrasts{1}, '_', sub, '.nii']};
    Sbetas(t, :) = cellfun(@mean_beta, con_file);
    cd('..');
end


means = struct;
means.mean_Sbetas = nanmean(Sbetas, 1);
means.sem_Sbetas = nanstd(Sbetas)/sqrt(length(subj_ids));


    function m = mean_beta(con_file)
        voxels = spm_get_data(con_file, included_voxels);
        m = nanmean(voxels);
    end
end