% run "choose left" (here: actually "choose onscreen food") regressions 
% for each participant and calculate weighted food values out of their
% taste and health weights and the taste and health ratings on each trial


bpath = '~/mrdata/ESC/behavior/';
rpath = [bpath 'cL_regressions/'];
mkdir(rpath)

% all participants who are included in the dietary choice analyses
subs = {'1003', ...
    '1004', ...
    '1006', ...
    '1007', ...
    '1008', ...
    '1009', ...
    '1012', ...
    '1014', ...
    '1015', ...
    '1016', ...
    '1018', ...
    '1019', ...
    '1020', ...
    '1021', ...
    '1023', ...
    '1027', ...
    '1030', ...
    '1032', ...
    '1034', ...
    '1037', ...
    '1038', ...
    '1039', ...
    '1040', ...
    '1043', ...
    '1046', ...
    '1047', ...
    '1049', ...
    '1050', ...
    '1052', ...
    '1054', ...
    '1060', ...
    '1062', ...
    '1066', ...
    '1067', ...
    '1068', ...
    '1071', ...
    '1072'};

nTrials = 100; % number of trials in the food choice task
condition = NaN(nTrials,3,length(subs)); % condition matrix for the regression

for i = 1:length(subs) % for each participant included in the food choice analyses
    hr = load([bpath 'results_health_' subs{i}], 'responses'); % all health ratings by this participant
    tr = load([bpath 'results_taste_' subs{i}], 'responses'); % all taste ratings by this participant
    img = load([bpath 'imagelist_' subs{i}]);
    
    condition(:,1,i) = hr.responses(img.imgvect.blocks)-213; % read in health rating + subtract neutral
    condition(:,2,i) = tr.responses(img.imgvect.blocks)-213; % read in taste rating + subtract neutral
    
    
    res = load([bpath 'food_choices_' subs{i}],'responses'); % load responses by this participant
    res.responses(res.responses == 2) = 0; % 1 = yes, 2 = no %re-code "no" to be zero
    condition(:,3,i) = res.responses;
    
    CT = ~isnan(condition(:,3,i));
    
    [b,~,stats] = glmfit(condition(CT,1:2,i),condition(CT,3,i), 'binomial', 'link', 'logit');
    betas(i,:) = b; %intercept, health, taste
    
end

save([rpath 'reg_chooseL_all'],'betas')

for i = 1:length(subs)
    % create weighted overall food value for each subject
    FV = (condition(:,1,i) .* betas(i,2)) + (condition(:,2,i) .* betas(i,3));
    
    save([rpath 'weighted_stimvals_' subs{i}], 'FV')
end
